### PR TITLE
implement 'snapshot' policy for out-of-date R / Bioc installations

### PR DESCRIPTION
**Pull request by mtmorgan**

### CODE REVIEW

**Comment by mtmorgan** [comment]
Test this by creating a file config.yaml with at least
```
r_ver_for_bioc_ver:
  "3.9": "3.6"
  "3.10": "3.6"
  "3.11": "4.0"
  "3.12": "4.0"
  "3.13": "4.1"
mran_ver_for_bioc_ver:     # usually the day before the *next* relesae
  "3.9": "10/28/2019"
  "3.10": "04/27/2020"
  "3.11": "10/28/2020"
rspm_ver_for_bioc_ver:     # usually the first day before the *next* release listed at https://packagemanager.rstudio.com/client/#/repos/2/overview
  "3.9": "10/28/2019"
  "3.10": "04/27/2020"
  "3.11": "10/28/2020"
```
Point the environment variable `BIOCONDUCTOR_CONFIG_FILE` to this file, 
```
$ export BIOCONDUCTOR_CONFIG_FILE=/path/to/config.yaml
```
Then in in R and using a version of Bioconductor in the config file, set the snapshot source
```
 options(BiocManager.snapshot = "RSPM")
 BiocManager::repositories()
options(BiocManager.snapshot = "MRAN")
BiocManager::repositories()
```
MRAN will be chosen by default for release 3.12 and later, once release 3.13 is available.

**Comment by LiNk-NY** [comment]
Hi Martin, @mtmorgan 
I am getting an error when installing the package with the above ENV var set and the option `options(BiocManager.snapshot = "RSPM")`:

### Error
```r
> Rdev --vanilla CMD INSTALL BiocManager
* installing to library ‘/home/mramos/R/bioc-devel’
* installing *source* package ‘BiocManager’ ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘BiocManager’:
 .onLoad failed in loadNamespace() for 'BiocManager', details:
  call: if (is.na(version)) version <- .VERSION_UNKNOWN
  error: argument is of length zero
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/mramos/R/bioc-devel/BiocManager’
###
```
###  R version
```r
> Rdev -e "R.version"               _                                                 
platform       x86_64-pc-linux-gnu                               
arch           x86_64                                            
os             linux-gnu                                         
system         x86_64, linux-gnu                                 
status         Under development (unstable)                      
major          4                                                 
minor          1.0                                               
year           2021                                              
month          01                                                
day            14                                                
svn rev        79831                                             
language       R                                                 
version.string R Under development (unstable) (2021-01-14 r79831)
nickname       Unsuffered Consequences      
```
### Config file
```sh
$ echo $BIOCONDUCTOR_CONFIG_FILE
/home/mramos/test/config.yaml
$ cat $BIOCONDUCTOR_CONFIG_FILE
r_ver_for_bioc_ver:
  "3.9": "3.6"
  "3.10": "3.6"
  "3.11": "4.0"
  "3.12": "4.0"
  "3.13": "4.1"
mran_ver_for_bioc_ver:     # usually the day before the *next* relesae
  "3.9": "10/28/2019"
  "3.10": "04/27/2020"
  "3.11": "10/28/2020"
rspm_ver_for_bioc_ver:     # usually the first day before the *next* release listed at https://packagemanager.rstudio.com/client/#/repos/2/overview
  "3.9": "10/28/2019"
  "3.10": "04/27/2020"
  "3.11": "10/28/2020"
```
### .Rprofile 

```r
options(
    BiocManager.snapshot = "RSPM",
    useFancyQuotes = FALSE,
    Ncpus = 3
)

```

**Comment by mtmorgan** [comment]
@LiNk-NY thanks; the minimal config file needs to know release and devel versions; I've added
```
release_version: "3.12"
devel_version: "3.13"
```
to the top of the config file in the first comment.

**Comment by LiNk-NY** [comment]
Hi Martin, @mtmorgan 
I've tested this and it works with R-oldrel 3.6.3. It looks good to me. 
Best,
Marcel

**Review by LiNk-NY — APPROVED** [review]

**Comment by vjcitn** [comment]
I think you've identified (in the email) a source of concern.  BiocManager::install should IMHO stick to a limited scope.  I feel that overwriting installed CRAN packages with older versions is out of scope.   If it is felt that this is a high value operation, a parameter synchronizeWithMRAN defaulting to FALSE might help defuse potentially problematic situations.  Warnings about potential inconsistencies would probably be nice for the install operation, and it seems you have the data to help with that.

**Comment by hpages** [comment]
So IIUC if you are using BioC 3.11 and you already have the latest CRAN packages installed, installing Bioconductor packages with `BiocManager::install()` won't automatically downgrade the CRAN packages and won't tell you anything. You'll only find out that your CRAN packages are out-of-sync with BioC 3.11 if you run `BiocManager::valid()` and then you'll resync them by just reinstalling them. Am I understanding this correctly?

**Comment by mtmorgan** [comment]
@hpages yes, like install.packages(), BiocManager::install() will only downgrade the package if it is explicitly mentioned `BiocManager::install("TooNewPackage")`

BiocManager::valid() will report that there are x packages that are too new, and will provide a cut-and-paste command that includes the too-new package (as well as out-of-date packages), and the output of BiocManager::valid() is relatively noise -- it would be easy for the user to miss that they were downgrading one or more CRAN packages.

One possibility would be for BiocManager::valid() to report a warning() when a downgrade would result...

**Comment by mtmorgan** [comment]
I adjusted this to support snapshot dates, but this behavior is not the default -- the user 'opts in' to this best practice, rather than being taken unawares.

**Pull request merged**
