### PR TITLE
Add Italian translation

### PR DESCRIPTION
**Pull request by LiNk-NY**
Possible reviewers: @drisso @drighelli @federicomarini ?

Thanks!

### CODE REVIEW

**Comment by federicomarini** [comment]
Hi Marcel, 
I'll be happy to take a look at the translations.
Shall I coordinate this with the other Italian fellows at best? We could probably use a google doc/sheet where it is easier to add comments to some of the formulations, which currently seem "too cold" - but maybe you used an automated translator for the first draft?
Federico

**Comment by drighelli** [comment]
Hi guys,

really happy to help and we can surely coordinate on the improvements, how do we want to proceed?

dario

**Comment by drisso** [comment]
Happy to help too!

@federicomarini if you want to copy over the text onto a google doc, we can all work on it and then edit the file once we have a final version of the translation.

**Comment by federicomarini** [comment]
Gdoc on its way, I'll share the link on Slack!

**Pull request merged**
