### PR TITLE
Rename cran repositories base

### PR DESCRIPTION
**Pull request by LiNk-NY**
This PR removes functionality for older versions from BiocManager including ad-hoc modifications to the map for expected date values. 
~Should be updated with https://github.com/seandavi/BiocPkgTools/pull/66~

### CODE REVIEW

**Comment by LiNk-NY** [comment]
Hi Martin @mtmorgan 
I'm in favor of removing the RSPM / MRAN codebase. I would modify it to not mention `BiocPkgTools` and maybe make a note somewhere to direct users to `Bioconductor/BiocArchive`. 
Thoughts?

**Comment by mtmorgan** [comment]
yes I'm in favor of these changes

**Comment by LiNk-NY** [comment]
Hi Martin, @mtmorgan 
This is ready. I can squash and merge with your approval. 
I want to submit this as part of the next release, if possible. 
I've tested this on old-rel, rel, and devel and it passes. `revdepcheck` doesn't show any errors.

**Review by mtmorgan — APPROVED** [review]
Looks good to me, thanks!

**Pull request closed without merging**
