### PR TITLE
Added the Spanish translation for some messages. Updated README-Translation.md

### PR DESCRIPTION
**Pull request by rcastelo**
I've tried to implement some translation to Spanish. Following the document [Translating R messages](https://developer.r-project.org/Translations30.html), I have first run this command on the `po` directory:

```
msginit -i R-BiocManager.pot -o R-es.po
```
Then I have translated some messages in `R-es.po`, for instance:

```
msgid "installing package(s) %s"
msgstr "instalando paquete(s) %s"
```

However, I wasn't sure about how to proceed with those in the multi-line format such as:

```
msgid ""
"'loadNamespace(\"remotes\")' failed:\n"
"    %s"
msgstr ""
```
and haven't attempted translating those. Anyway, it seems that my efforts haven't been successful somehow, because if I run R and load BiocManager under the Spanish locale `es_ES` I'm still not getting the Spanish translation:

```
$ LC_ALL="es_ES"
$ R

R version 4.0.3 (2020-10-10) -- "Bunny-Wunnies Freak Out"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin17.0 (64-bit)

R es un software libre y viene sin GARANTIA ALGUNA.
Usted puede redistribuirlo bajo ciertas circunstancias.
Escriba 'license()' o 'licence()' para detalles de distribucion.

R es un proyecto colaborativo con muchos contribuyentes.
Escriba 'contributors()' para obtener más información y
'citation()' para saber cómo citar R o paquetes de R en publicaciones.

Escriba 'demo()' para demostraciones, 'help()' para el sistema on-line de ayuda,
o 'help.start()' para abrir el sistema de ayuda HTML con su navegador.
Escriba 'q()' para salir de R.

> library(BiocManager)
Bioconductor version 3.12 (BiocManager 1.30.15.4), R 4.0.3 (2020-10-10)
Bioconductor version '3.12' is out-of-date; the current release version '3.13'
  is available with R version '4.1'; see https://bioconductor.org/install
> BiocManager::install("DESeq2", force=TRUE)
Bioconductor version 3.12 (BiocManager 1.30.15.4), R 4.0.3 (2020-10-10)
installing package(s) 'DESeq2'
probando la URL 'https://bioconductor.org/packages/3.12/bioc/bin/macosx/contrib/4.0/DESeq2_1.30.1.tgz'
Content type 'application/x-gzip' length 1909248 bytes (1.8 MB)
==================================================
downloaded 1.8 MB
```
As you can see, `BiocManager` says "installing package(s) 'DESeq2'" instead of "instalando paquete(s) 'DESeq2'", which is in principle part of the implemented translations, while R correctly says in Spanish "probando la URL ...". So, something must be missing here. The R page [Translating R messages](https://developer.r-project.org/Translations30.html) talks about having two files, in the example `R-spline.pot` and `splines.pot`, while in the `po` directory there's only one `R-BiocManager.pot` and not the `BiocManager.pot`. I hope that at least with the `R-es.po` file you can find out what the missing bit is here.

I have also made some minor edits in the `README-Translation.md` file, concretely I think there are no locales for dialects, which are a particular form of a language which is peculiar to a specific region or social group, but for varieties that have sufficiently diverged from a language, such as Mexican Spanish, which has the locale `es_MX` (see [here](https://www.localeplanet.com/icu/es/index.html) and [here](https://en.wikipedia.org/wiki/Spanish_dialects_and_varieties)). [Catalan](https://en.wikipedia.org/wiki/Catalan_language) is a language on its own and has its own locale [ca_ES](https://www.localeplanet.com/icu/ca-ES/index.html).

### CODE REVIEW

**Comment by mtmorgan** [comment]
I believe R-splines.pot is for messages in the R code of splines, whereas splines.pot is for messages in C code. BiocManager does not have any C code.

I think there's a step to translate the .po to .mo file, mentioned in the README-Translations.md as ('en' in the path to the .mo file and in the .po file needed to be changed to 'es' from the example)
```
BiocManager/po rcastelo-po-translations$ msgfmt -c --statistics -o ../inst/po/es/LC_MESSAGES/R-BiocManager.mo R-es.po
```
but this leads to
```
R-es.po:49:13: invalid multibyte sequence
R-es.po:96:34: invalid multibyte sequence
R-es.po:99:20: invalid multibyte sequence
R-es.po:102:27: invalid multibyte sequence
R-es.po:105:14: invalid multibyte sequence
R-es.po:105:27: invalid multibyte sequence
R-es.po:108:27: invalid multibyte sequence
R-es.po:114:66: invalid multibyte sequence
R-es.po:117:27: invalid multibyte sequence
R-es.po:117:51: invalid multibyte sequence
msgfmt: found 10 fatal errors
```
Taking the first one, I see
```
msgstr "opci\303n..."
```
whereas I think it should be
```
msgstr "opción..."
```
i.e., the encoding of the text is not correct.

I'm not really sure about the multi-line messages -- I think the idea is to translate into something similarly formatted, but not line-for-line. For instance, in base R I see at https://github.com/wch/r-source/blob/da944f2022f60c11c4d70f5320ef18163b0a10cc/src/library/base/po/es.po#L1035-L1039
```
msgid ""
"data length [%d] is not a sub-multiple or multiple of the number of rows [%d]"
msgstr ""
"la longitud de los datos [%d] no es un submúltiplo o múltiplo del número de "
"filas [%d] en la matriz"
```

**Comment by rcastelo** [comment]
I've added the translation for multi-line messages and set the encoding of the file to ISO8859-1 as in the [src/library/base/po/es.po](https://github.com/wch/r-source/blob/da944f2022f60c11c4d70f5320ef18163b0a10cc/src/library/base/po/es.po) file from R sources. Then, I created the directory `BiocManager/inst/po/es/LC_MESSAGES` and ran:

```
$ msgfmt -c --statistics -o ../inst/po/es/LC_MESSAGES/R-BiocManager.mo R-es.po
```

from the `BiocManager/po` directory. I noticed that still the first messages are not translated:

```
> library(BiocManager)
Bioconductor version 3.12 (BiocManager 1.30.15.4), R 4.0.3 (2020-10-10)
Bioconductor version '3.12' is out-of-date; the current release version '3.13'
  is available with R version '4.1'; see https://bioconductor.org/install
```
and replaced the two `sprintf()` calls in `.version_recommend()` to `.msg()` calls, which I thought is the way in which messages should be given to enable translations, but those messages keep showing without translation. The rest of the interactions seem to be translated, though:

```
BiocManager::install("DESeq2")
Warning message:
uno o más paquetes no han sido instalados porque sus versiones son las mismas
  que las actuales; utiliza `force = TRUE` para re-instalar: 'DESeq2' 
BiocManager::install("DESeq2", force=TRUE)
Bioconductor version 3.12 (BiocManager 1.30.15.4), R 4.0.3 (2020-10-10)
instalando paquete(s) 'DESeq2'
probando la URL 'https://bioconductor.org/packages/3.12/bioc/bin/macosx/contrib/4.0/DESeq2_1.30.1.tgz'
Content type 'application/x-gzip' length 1909248 bytes (1.8 MB)
==================================================
downloaded 1.8 MB
```
so this first message that informs about the Bioconductor version, keeps showing untranslated, but I think we're close to having a first Spanish version of BiocManager :)

**Comment by mtmorgan** [comment]
I'll take a look at this, but wanted to mention that I don't think `sprintf()` -> `.msg()` is the correct change -- I think you want to use `gettext()` [not sure if that's the correct function...] to translate the `fmt=` of `sprintf()`; the function returns a string to indicated 'something went wrong', otherwise it returns TRUE. The behavior of the calling function changes depending on the return value. Mentioning this because https://github.com/Bioconductor/BiocManager/pull/109 also wants to change sprintf...

**Comment by LiNk-NY** [comment]
Hi Martin, @mtmorgan 

Maybe I'm not seeing what you're seeing but `.msg` does use `gettext` and it returns the text not `TRUE`. 

https://github.com/Bioconductor/BiocManager/blob/512abec06dc6e89243543e983b04fdd5612df7ae/R/utilities.R#L35-L52

**Comment by mtmorgan** [comment]
I think lines 42 & 43 should just be `txt <- gettextf(fmt, ...)`. Roberto mentioned the two `sprintf()` calls in `.version_recommend()`, which I think should be (I'm working on this) changed to 
```
--- a/R/version.R
+++ b/R/version.R
@@ -228,7 +228,7 @@ format.version_sentinel <-
 .version_string <-
     function(bioc_version = version())
 {
-    sprintf(
+    gettextf(
         "Bioconductor version %s (BiocManager %s), %s",
         bioc_version, packageVersion("BiocManager"),
         sub(" version", "", R.version.string)
@@ -250,7 +250,7 @@ format.version_sentinel <-
         return(.version_sentinel_msg(version))
 
     if (version[, 1:2] != version)
-        return(sprintf(
+        return(gettextf(
             "version '%s' must have two components, e.g., '3.7'", version
         ))
```

**Pull request closed without merging**
